export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_PENDING = 'FETCH_USER_PENDING';
export const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED';
export const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED';

export const FETCH_REPOS = 'FETCH_REPOS';
export const FETCH_REPOS_PENDING = 'FETCH_REPOS_PENDING';
export const FETCH_REPOS_FULFILLED = 'FETCH_REPOS_FULFILLED';
export const FETCH_REPOS_REJECTED = 'FETCH_REPOS_REJECTED';
